chat:
  description: Chat with Poe
  fields:
    name:
      description: Config entity name
      example: poe
      required: true
      selector:
        text:
    bot:
      description: Bot ID
      example: capybara
      required: false
      selector:
        text:
    message:
      description: Message to send. If there is no message and 'reconnect_ws' is 'True', the websocket will be reconnected without sending a message
      example: Hello
      required: false
      selector:
        text:
    conversation_id:
      description: Conversation ID
      required: false
      selector:
        text:
    reconnect_ws:
      description: Reconnect the websocket before sending the message
      required: false
      example: false
      selector: 
        boolean:
    throw:
      description: Throw reply
      default: false
      example: false
      selector:
        boolean:
    throw_chunk:
      description: Throw reply chunked
      default: false
      example: true
      selector:
        boolean:
